run over the samples name from sample2bc instead of run over  a folder
Webiks/IgomeProfiling pull request #13
Opened 2020-12-16 12:53 UTC by yael1994

2021-04-21 08:34 UTC, yael1994 commented
https://trello.com/c/GeWVzFy9/23-merge-meme-by-sample2bc-file-and-not-overall-the-dir

2021-04-25 14:24 UTC, shacharmo requested changes

2021-04-25 14:24 UTC, shacharmo commented on motif_inference/merge_meme_files.py
> +from auxiliaries.pipeline_auxiliaries import *
Done use implicit import, always specify exactly what is required to import

2021-04-25 14:24 UTC, shacharmo commented on motif_inference/merge_meme_files.py
> +    print(list_sample_of_bc)
Do we want to print it or it was just for debugging?

2021-04-27 19:58 UTC, shacharmo approved these changes

2021-04-27 19:58 UTC, merged