change the place of file AWS stop machines from tools to auxiliaries
Webiks/IgomeProfiling pull request #27
Opened 2021-05-23 14:27 UTC by yael1994

2021-05-23 14:29 UTC, yael1994 commented
https://trello.com/c/IdmWqueG/30-moving-aws-machines-stop-from-tools-to-aux

2021-05-23 17:17 UTC, shacharmo requested changes

2021-05-23 17:17 UTC, shacharmo commented on reads_filtration/module_wraper.py
> +from global_params import src_dir
Is this needed? src_dir is defined in above lines and we always run the pipeline from main directory

2021-05-25 16:38 UTC, shacharmo approved these changes

2021-05-25 16:38 UTC, merged