Extract params cutoffs
Webiks/IgomeProfiling pull request #40
Opened 2021-07-13 10:51 UTC by yael1994

2021-07-13 11:08 UTC, yael1994 commented
https://trello.com/c/3QmTEJbr/45-extract-percentofrandomhitsperpssm-of-the-pipeline-from-pssmscorepeptide-file

2021-07-13 16:32 UTC, shacharmo requested changes

2021-07-13 16:32 UTC, shacharmo commented on IgOmeProfiling_pipeline.py
> +    parser.add_argument('--precent_random_hit_pssm', type=float, default=0.05, help='Precent of random hits per PSSM, for calculate cutoffs')
The name and help isn't very indicative/explanatory.
What it does is taken the score to top percentile of random peptides and define it a cutoff score, i.e., peptide with score equal or greater than cutoff is considered as hit.

Parameter name should be something similar to `cutoff_random_peptitdes_percentile`.

This comment is applicable to all the code change in this PR

2021-07-14 09:43 UTC, shacharmo requested changes

2021-07-14 09:43 UTC, shacharmo commented on IgOmeProfiling_pipeline.py
> +    parser.add_argument('--cutoff_random_peptitdes_percentile', type=float, default=0.05, help='Set the top percentile of random peptides and define it a cutoff score')
Change help to "Calculate cutoff (hit threshold) from random peptides' top percentile score"

2021-07-14 09:58 UTC, shacharmo approved these changes

2021-07-14 09:58 UTC, merged